import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LinkedInIcon, XIcon } from "@/components/landing/icons";
import { LogoWall } from "@/components/landing/logo-wall";

export function Hero() {
  return (
    <section className="relative overflow-hidden sky-backdrop pt-32 pb-16 sm:pt-36 sm:pb-24 xl:pt-44 2xl:pt-48">
      <div className="mx-auto w-full max-w-[1920px] px-5 sm:px-8 lg:px-12 2xl:px-16">
        <div className="mx-auto flex max-w-4xl flex-col items-center text-center">
          <div className="inline-flex items-center gap-2.5 rounded-full bg-white/85 px-4 py-2 shadow-sm ring-1 ring-white/60 backdrop-blur xl:px-5 xl:py-2.5">
            <XIcon className="size-3.5 text-ink xl:size-4" />
            <LinkedInIcon className="size-4 xl:size-5" />
            <span className="text-[0.8125rem] font-medium text-ink/80 xl:text-[1.0625rem]">
              Where B2B brands work with creators
            </span>
          </div>

          <h1 className="mt-8 max-w-[15ch] font-display text-[2.75rem] leading-[1.03] font-semibold tracking-[-0.035em] text-ink sm:text-6xl lg:text-7xl xl:text-[5.25rem] 2xl:text-[6rem]">
            The B2B LinkedIn Creator Marketplace.
          </h1>

          <p className="mt-6 max-w-xl text-base leading-relaxed text-ink/65 sm:text-lg xl:max-w-[46rem] xl:text-2xl">
            Find the creators your buyers already trust, launch campaigns in
            days, and track the clicks, leads and pipeline generated by every
            post.
          </p>

          <div className="mt-9 flex flex-col items-center gap-4 sm:flex-row sm:gap-6 xl:mt-12 xl:gap-8">
            <Button render={<Link href="/signup" />}
              size="lg"
              className="group h-12 rounded-full bg-ink px-7 text-[0.9375rem] text-white hover:bg-ink/90 xl:h-14 xl:px-8 xl:text-[1.0625rem]">
                Launch a campaign
                <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
              </Button>
            <Link
              href="#how-it-works"
              className="group inline-flex items-center gap-2 text-[0.9375rem] font-medium text-ink xl:text-[1.0625rem]"
            >
              See how Naano works
              <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>

          <p className="mt-10 inline-flex items-center gap-2 text-[0.8125rem] text-ink/55 xl:mt-14 xl:text-[0.9375rem]">
            <ShieldCheck className="size-4" />
            Trusted by modern B2B teams
          </p>
        </div>
      </div>

      <LogoWall />
    </section>
  );
}
