import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LinkedInIcon, XIcon } from "@/components/landing/icons";
import { LogoWall } from "@/components/landing/logo-wall";

export function Hero() {
  return (
    <section className="relative overflow-hidden sky-backdrop pt-28 pb-16 sm:pt-32 sm:pb-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto flex max-w-3xl flex-col items-center text-center">
          <div className="inline-flex items-center gap-2 rounded-full bg-white/85 px-4 py-2 shadow-sm ring-1 ring-white/60 backdrop-blur">
            <XIcon className="size-3.5 text-ink" />
            <LinkedInIcon className="size-4" />
            <span className="text-[0.8125rem] font-medium text-ink/80">
              Where B2B brands work with creators
            </span>
          </div>

          <h1 className="mt-8 max-w-[15ch] font-display text-[2.75rem] leading-[1.04] font-semibold tracking-[-0.03em] text-ink sm:text-6xl lg:text-[4.25rem]">
            The B2B LinkedIn Creator Marketplace.
          </h1>

          <p className="mt-6 max-w-xl text-base leading-relaxed text-ink/65 sm:text-lg">
            Find the creators your buyers already trust, launch campaigns in
            days, and track the clicks, leads and pipeline generated by every
            post.
          </p>

          <div className="mt-9 flex flex-col items-center gap-4 sm:flex-row sm:gap-6">
            <Button render={<Link href="/signup" />}
              size="lg"
              className="group rounded-full bg-ink px-6 text-white hover:bg-ink/90">
                Launch a campaign
                <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
              </Button>
            <Link
              href="#how-it-works"
              className="group inline-flex items-center gap-2 text-sm font-medium text-ink"
            >
              See how Naano works
              <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>

          <p className="mt-10 inline-flex items-center gap-2 text-[0.8125rem] text-ink/55">
            <ShieldCheck className="size-4" />
            Trusted by modern B2B teams
          </p>
        </div>
      </div>

      <LogoWall />
    </section>
  );
}
