import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import { GlobalAssistantBar } from "@/components/global-assistant-bar";
import { AssistantProvider } from "@/components/assistant/assistant-context";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

// Naano sets headings in a tight geometric sans; Outfit is the closest free match.
const outfit = Outfit({
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Naano — The B2B LinkedIn Creator Marketplace",
  description:
    "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AssistantProvider>
          {children}
          <GlobalAssistantBar />
        </AssistantProvider>
      </body>
    </html>
  );
}
